#!/usr/bin/env python
sample = input("File name : ")
with open(sample + ".txt") as r_sample:
    s, t = r_sample.read().splitlines()

positions = ""

# Solution 1
for i in range(len(s)):
    if t[0] == s[i]:
        if t == s[i : i + len(t)]:
            positions += str(i + 1) + " "

# #Solution 2
# for i in range(len(s)):
#     if s[i:].startswith(t):
#         positions += str(i + 1) + " "

print(positions)
