#!/usr/bin/env python
sample = input("File name : ")
r_sample = open(sample + ".txt", "r")
l_seq = []

for line in r_sample:
    if line.startswith(">"):
        b = ""
    else:
        if b == "":
            b = line.strip()
            l_seq.append(b)
        else:
            b = line.strip()
            l_seq[-1] = l_seq[-1] + b

short_seq = l_seq[0]
comp_seq = l_seq[1:]
motif = ""

for i in range(len(short_seq)):
    for j in range(i, len(short_seq)):
        m = short_seq[i : j + 1]
        found = False
        for sequ in comp_seq:
            if m in sequ:
                found = True
            else:
                found = False
                break
        if found and len(m) > len(motif):
            motif = m
print("Copy to the Answer submission ;", motif)
